### PR TITLE
Android Update + Restructure

### PR DESCRIPTION
**Pull request by m1ga**
**Do not merge yet**

* Updated Android version to use Titanium SDK 9
* Updated Android version to use adjust-android:4.24.0 (gradle)
* Changed the structure (removed unused folders) so it is more inline with the Ti module structure
* Verified the module with the demo app

### CODE REVIEW

**Comment by m1ga** [comment]
Good to head @ugi ! I've tested it with the included demo app and it looks like it is working fine.

**Comment by ugi** [comment]
Wow, nice. Thanks for devotion, really appreciated. We still have few non native SDKs in update queue prior to Titanium, but will keep you posted.

**Comment by m1ga** [comment]
:+1: sounds good! Awesome that you'll support Ti. And if people update to the newest Ti SDK 9 they know it'll will work if they use this PR

**Comment by ugi** [comment]
@m1ga I just wanna thank you one more time for the PR, but there was just too many changes to start from there our big update since a while ago. So, replacing this one with pretty much changes you made + many more in [here](https://github.com/adjust/titanium_sdk/pull/23). Thank you one more time and cheers! 🍺

**Comment by m1ga** [comment]
:+1: nice! There are some files you could remove (e.g. gitignore) like mainfest.bak, build.properties and you could remove the lib's inside the lib folder and use build.gradle (don't need to sync that folder all the time). But that are just small cosmetic corrections and not really needed :smile: Again: big thanks for keeping the Titanium module up-to-date!

**Pull request closed without merging**
